# Generated by Django 4.2.4 on 2023-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUDUSD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EURUSD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GPBUSD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USDCHF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USDJPY',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='XAUUSD',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
    ]
