# Generated by Django 4.2.4 on 2023-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('symbol', models.TextField(max_length=10)),
                ('open', models.FloatField(max_length=10)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AUDUSD',
        ),
        migrations.DeleteModel(
            name='EURUSD',
        ),
        migrations.DeleteModel(
            name='GPBUSD',
        ),
        migrations.DeleteModel(
            name='USDCHF',
        ),
        migrations.DeleteModel(
            name='USDJPY',
        ),
        migrations.DeleteModel(
            name='XAUUSD',
        ),
    ]
