# Generated by Django 4.2.4 on 2023-08-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_symbol_delete_audusd_delete_eurusd_delete_gpbusd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='datetime',
        ),
    ]
