# Generated by Django 4.2.4 on 2023-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_symbol_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
